merge master

diff --git a/bin/ch-convert b/bin/ch-convert
--- a/bin/ch-convert
+++ b/bin/ch-convert
@@ -40,10 +40,13 @@ cv_chimage_dir () {
 cv_chimage_docker () {
     chimage_in_validate "$1"
     docker_out_validate "$2"
-    chimage_tar=${tmpdir}/weirdal.tar.gz
-    cv_chimage_tar "$1" "$chimage_tar"  # FIXME: needlessly compresses?
-    cv_tar_docker "$chimage_tar" "$2"
-    rm "$chimage_tar"
+    chimage_to_dockman docker_ "$1" "$2"
+}
+
+cv_chimage_podman () {
+    chimage_in_validate "$1"
+    podman_out_validate "$2"
+    chimage_to_dockman podman_ "$1" "$2"
 }
 
 cv_chimage_squash () {
@@ -71,13 +74,13 @@ cv_dir_chimage () {
 cv_dir_docker () {
     dir_in_validate "$1"
     docker_out_validate "$2"
-    dirtar=${tmpdir}/weirdal.tar.gz
-    # One could also use "docker build" with "FROM scratch" and "COPY",
-    # apparently saving a tar step. However, this will in fact tar the source
-    # directory anyway to send it to the Docker daemon.
-    cv_dir_tar "$1" "$dirtar"  # FIXME: needlessly compresses
-    cv_tar_docker "$dirtar" "$2"
-    rm "$dirtar"
+    dir_to_dockman docker_ "$1" "$2"
+}
+
+cv_dir_podman () {
+    dir_in_validate "$1"
+    podman_out_validate "$2"
+    dir_to_dockman podman_ "$1" "$2"
 }
 
 cv_dir_squash () {
@@ -110,50 +113,69 @@ cv_dir_tar () {
 }
 
 cv_docker_chimage () {
-   docker_in_validate "$1"
+   dockman_in_validate docker_ "$1"
    chimage_out_validate "$2"
-   docker_out=${tmpdir}/weirdal.tar.gz
-   cv_docker_tar "$1" "$docker_out"  # FIXME: needlessly compresses
-   cv_tar_chimage "$docker_out" "$2"
-   rm "$docker_out"
+   dockman_to_chimage docker_ "$1" "$2"
 }
 
 cv_docker_dir () {
-    docker_in_validate "$1"
+    dockman_in_validate docker_ "$1"
     dir_out_validate "$2"
+    dockman_to_dir docker_ "$1" "$2"
+}
+
+cv_docker_podman () {
+    dockman_in_validate docker_ "$1"
+    podman_out_validate "$2"
     docker_out=${tmpdir}/weirdal.tar.gz
-    cv_docker_tar "$1" "$docker_out"  # FIXME: needlessly compresses
-    cv_tar_dir "$docker_out" "$2"
+    cv_docker_tar "$1" "$docker_out" # FIXME: needlessly compresses
+    cv_tar_podman "$docker_out" "$2"
     rm "$docker_out"
 }
 
 cv_docker_squash () {
-    docker_in_validate "$1"
+    dockman_in_validate docker_ "$1"
     squash_out_validate "$2"
-    docker_dir=${tmpdir}/weirdal
-    cv_docker_dir "$1" "$docker_dir"  # FIXME: needlessly compresses
-    cv_dir_squash "$docker_dir" "$2"
-    rm -Rf --one-file-system "$docker_dir"
+    dockman_to_squash docker_ "$1" "$2"
 }
 
 cv_docker_tar () {
-    docker_in_validate "$1"
+    dockman_in_validate docker_ "$1"
     tar_out_validate "$2"
-    tmptar=${tmpdir}/weirdal.tar
-    tmpenv=${tmpdir}/weirdal.env
-    INFO 'exporting ...'
-    cid=$(docker_ create --read-only "$1" /bin/true)  # cmd needed but not run
-    size=$(docker_ image inspect "$1" --format='{{.Size}}')
-    docker_ export "$cid" | pv_ -s "$size" > "$tmptar"
-    docker_ rm "$cid" > /dev/null
-    INFO 'adding environment ...'
-    docker_ inspect "$1" \
-            --format='{{range .Config.Env}}{{println .}}{{end}}' > "$tmpenv"
-    tar rf "$tmptar" -b1 -P --xform="s|${tmpenv}|ch/environment|" "$tmpenv"
-    INFO 'compressing ...'
-    pv_ < "$tmptar" | gzip_ -6 > "$2"
-    rm "$tmptar"
-    rm "$tmpenv"
+    dockman_to_tar docker_ "$1" "$2"
+}
+
+cv_podman_chimage () {
+    dockman_in_validate podman_ "$1"
+    chimage_out_validate "$2"
+    dockman_to_chimage podman_ "$1" "$2"
+}
+
+cv_podman_dir () {
+    dockman_in_validate podman_ "$1"
+    dir_out_validate "$2"
+    dockman_to_dir podman_ "$1" "$2"
+}
+
+cv_podman_docker () {
+    dockman_in_validate podman_ "$1"
+    docker_out_validate "$2"
+    podman_out=${tmpdir}/weirdal.tar.gz
+    cv_podman_tar "$1" "$podman_out" # FIXME: needlesly compresses
+    cv_tar_docker "$podman_out" "$2"
+    rm "$podman_out"
+}
+
+cv_podman_squash () {
+    dockman_in_validate podman_ "$1"
+    squash_out_validate "$2"
+    dockman_to_squash podman_ "$1" "$2"
+}
+
+cv_podman_tar () {
+    dockman_in_validate podman_ "$1"
+    tar_out_validate "$2"
+    dockman_to_tar podman_ "$1" "$2"
 }
 
 cv_squash_chimage () {
@@ -187,10 +209,13 @@ cv_squash_dir () {
 cv_squash_docker () {
     squash_in_validate "$1"
     docker_out_validate "$2"
-    unsquash_tar=${tmpdir}/weirdal.tar.gz
-    cv_squash_tar "$1" "$unsquash_tar"
-    cv_tar_docker "$unsquash_tar" "$2"
-    rm "$unsquash_tar"
+    squash_to_dockman docker_ "$1" "$2"
+}
+
+cv_squash_podman () {
+    squash_in_validate "$1"
+    podman_out_validate "$2"
+    squash_to_dockman podman_ "$1" "$2"
 }
 
 cv_squash_tar () {
@@ -257,8 +282,13 @@ cv_tar_dir () {
 cv_tar_docker () {
     tar_in_validate "$1"
     docker_out_validate "$2"
-    INFO "importing ..."
-    docker_ import "$1" "$2"  # FIXME: no progress meter
+    tar_to_dockman docker_ "$1" "$2"    
+}
+
+cv_tar_podman () {
+    tar_in_validate "$1"
+    podman_out_validate "$2"
+    tar_to_dockman podman_ "$1" "$2"
 }
 
 cv_tar_squash () {
@@ -270,6 +300,110 @@ cv_tar_squash () {
     rm -Rf --one-file-system "$tar_dir"
 }
 
+## Dockman functions ##
+
+# Use for conversions involving docker or podman. Similarities between the
+# command line instructions for docker and podman allow to write generalized
+# functions that can be used for both (hence 'dockman'). When calling a
+# 'dockman' function, image format is specified by the first argument
+# ('docker_' or 'podman_').
+
+chimage_to_dockman () {
+    chimage_tar=${tmpdir}/weirdal.tar.gz
+    cv_chimage_tar "$2" "$chimage_tar"  # FIXME: needlessly compresses?
+    tar_to_dockman "$1" "$chimage_tar" "$3"
+    rm "$chimage_tar"
+}
+
+dir_to_dockman () {
+    dirtar=${tmpdir}/weirdal.tar.gz
+    # One could also use "docker build" with "FROM scratch" and "COPY",
+    # apparently saving a tar step. However, this will in fact tar the source
+    # directory anyway to send it to the Docker daemon.
+    cv_dir_tar "$2" "$dirtar"  # FIXME: needlessly compresses
+    tar_to_dockman "$1" "$dirtar" "$3"
+    rm "$dirtar"
+}
+
+dm_fmt_name () {
+    # Format 'docker_' and 'podman_' as 'Docker' and 'Podman' respectively.
+    case $1 in
+	docker_)
+	    echo "$1" | tr "d" "D" | tr -d "_"
+	    ;;
+	podman_)
+	    echo "$1" | tr "p" "P" | tr -d "_"
+	    ;;
+	*)
+	    FATAL "unreachable code reached"
+	    ;;
+    esac
+}
+
+dockman_in_validate () {
+    digest=$("$1" image ls -q "$2")
+    [ -n "$digest" ] || FATAL "source not found in $(dm_fmt_name "$1") storage: ${2}"
+}
+
+dockman_to_chimage () {
+   dockman_out=${tmpdir}/weirdal.tar.gz
+   "cv_${1}tar" "$2" "$dockman_out"  # FIXME: needlessly compresses
+   cv_tar_chimage "$dockman_out" "$3"
+   rm "$dockman_out"
+}
+
+dockman_to_dir () {
+    dockman_out=${tmpdir}/weirdal.tar.gz
+    "dockman_to_tar" "$1" "$2" "$dockman_out" # FIXME: needlessly compresses
+    cv_tar_dir "$dockman_out" "$3"
+    rm "$dockman_out"
+}
+
+dockman_to_squash () {
+    dockman_dir=${tmpdir}/weirdal
+    dockman_to_dir "$1" "$2" "$dockman_dir"  # FIXME: needlessly compresses
+    cv_dir_squash "$dockman_dir" "$3"
+    rm -Rf --one-file-system "$dockman_dir"
+}
+
+dockman_to_tar () {
+    tmptar=${tmpdir}/weirdal.tar
+    tmpenv=${tmpdir}/weirdal.env
+    INFO 'exporting ...'
+    cid=$("$1" create --read-only "$2" /bin/true)  # cmd needed but not run
+    size=$("$1" image inspect "$2" --format='{{.Size}}')
+    "$1" export "$cid" | pv_ -s "$size" > "$tmptar"
+    "$1" rm "$cid" > /dev/null
+    INFO 'adding environment ...'
+    "$1" inspect "$2" \
+            --format='{{range .Config.Env}}{{println .}}{{end}}' > "$tmpenv"
+    tar rf "$tmptar" -b1 -P --xform="s|${tmpenv}|ch/environment|" "$tmpenv"
+    INFO 'compressing ...'
+    pv_ < "$tmptar" | gzip_ -6 > "$3"
+    rm "$tmptar"
+    rm "$tmpenv"
+}
+
+squash_to_dockman () {
+    unsquash_tar=${tmpdir}/weirdal.tar.gz
+    cv_squash_tar "$2" "$unsquash_tar"
+    dockman=$(echo "$1" | tr -d "_") # remove trailing underscore
+    "cv_tar_$dockman" "$unsquash_tar" "$3"
+    rm "$unsquash_tar"
+}
+
+tar_to_dockman () {
+    INFO "importing ..."
+    tmpimg=$(mktemp -u tmpimg.XXXXXX | tr '[:upper:]' '[:lower:]')
+    "$1" import "$2" "$tmpimg"    # FIXME: no progress meter
+    # Podman imports our tarballs with rw------- permissions on “/ch” (i.e.,
+    # no execute), which causes all kinds of breakage. Work around that.
+    "$1" build -t "$3" - <<EOF
+FROM $tmpimg
+RUN chmod u+rwx /ch || true
+EOF
+    "$1" rmi "$tmpimg"
+}
 
 ## input/output validation functions #########################################
 
@@ -313,15 +447,23 @@ dir_out_validate () {
     fi
 }
 
-docker_in_validate () {
-    digest=$(docker_ image ls -q "$1")
-    [ -n "$digest" ] || FATAL "source not found in Docker storage: ${1}"
-}
-
 docker_out_validate () {
+    # When writing the out_validate functions, we had to address a podman bug
+    # that caused conversion to fail. Our workaround (see the 
+    # 'podman_out_validate' below) is not generalizable to docker, which is
+    # why we've broken from the 'dockman' convention here.
     digest=$(docker_ image ls -q "$1")
     if [ -n "$digest" ] && [ -n "$no_clobber" ]; then
-        FATAL "exists in Docker storage, not deleting per --no-clobber: ${1}"
+	FATAL "exists in Docker storage, not deleting per --no-clobber: ${1}"
+    fi
+}
+
+podman_out_validate () {
+    # Podman’s own image search is a substring query, so e.g. “foo” will also
+    # match “foobar”. Decades-old UNIX tools to the rescue. Thanks Red Hat!!
+    if    ( podman_ images | grep -Eq "^localhost/${1}\s" ) \
+       && [ -n "$no_clobber" ]; then
+	FATAL "exists in Podman storage, not deleting per --no-clobber: ${1}"
     fi
 }
 
@@ -368,7 +510,7 @@ desc_base () {
         dir)
             basename "$dsc"
             ;;
-        ch-image|docker)
+        ch-image|docker|podman)
             tag_to_path "$dsc"
             ;;
         squash)
@@ -387,7 +529,7 @@ desc_base () {
 dir_fixup () {
     DEBUG "fixing up: $1"
     # Make all directories writeable so we can delete later (hello, Red Hat).
-    find "$1" -type d -a ! -perm /200 -exec chmod u+w {} +
+    find "$1" -type d -a ! -perm -u+rwx -exec chmod u+w {} +
     # Ensure mount points are present.
     mount_points_ensure "$1"
 }
@@ -411,6 +553,8 @@ fmt_validate () {
             *)
                 if [ -n "$have_ch_image" ]; then
                     fmt=ch-image
+		elif [ -n "$have_podman" ]; then
+		    fmt=podman
                 elif [ -n "$have_docker" ]; then
                     fmt=docker
                 else
@@ -430,6 +574,11 @@ fmt_validate () {
                 FATAL "format docker invalid: docker not found"
             fi
             ;;
+	podman)
+	    if [ -z "$have_podman" ]; then
+		FATAL "format podman invalid: podman not found"
+	    fi
+	    ;;
         dir|squash|tar)
             ;;
         *)
@@ -658,6 +807,12 @@ if command -v docker > /dev/null 2>&1; then
     VERBOSE 'docker: found'
 else
     VERBOSE 'docker: not found'
+fi
+if command -v podman > /dev/null 2>&1; then
+    have_podman=yes
+    VERBOSE 'podman: found'
+else
+    VERBOSE 'podman: not found'
 fi
 
 in_fmt=$(fmt_validate "$in_fmt" "$in_desc")
