tidy

diff --git a/bin/ch-fromhost b/bin/ch-fromhost
--- a/bin/ch-fromhost
+++ b/bin/ch-fromhost
@@ -73,7 +73,7 @@ EOF
 )
 
 cray_mpi=          # Cray fixups requested
-#cray_openmpi=     # ... for OpenMPI
+cray_openmpi=      # ... for OpenMPI
 cray_mpich=        # ... for MPICH
 dest=
 image=
@@ -307,48 +307,48 @@ if [ $cray_mpich ]; then
 fi
 
 if [ $cray_openmpi ]; then
-    
-    # MPI_ROOT and MPIHOME are the base of the OpenMPI install tree
-    # using MPIHOME as some users unset MPI_ROOT
-        [ "$MPIHOME" ] \
-    || fatal "MPIHOME not set; is module openmpi loaded?"
-    
+    # Both MPI_ROOT and MPIHOME are the base of the OpenMPI install tree.
+    # We use MPIHOME because some users unset MPI_ROOT.
+    #
+    # Note also that the OpenMPI module name is not standardized.
+       [ "$MPIHOME" ] \
+    || fatal "MPIHOME not set; is OpenMPI module loaded?"
+
     # Inject libmpi from the host
-    host_libmpi=$(readlink -f "$MPIHOME/lib/libmpi.so")
+    host_libmpi=${MPIHOME}/lib/libmpi.so
         [ -f "$host_libmpi" ] \
-    || fatal "not found: ${host_libmpi}; is module openmpi loaded?"
+    || fatal "not found: ${host_libmpi}; is OpenMPI module loaded?"
     queue_files "$host_libmpi"
     queue_files "$(  ldd "$host_libmpi" \
                    | grep -E "/usr|/opt" \
-                   | sed -E 's/^.+ => (.+) \(0x.+\)$/\1/')" 
-
-    # This is appears to be the only .so required from /lib64
+                   | sed -E 's/^.+ => (.+) \(0x.+\)$/\1/')"
+    # This appears to be the only dependency in /lib64 that we can't get from
+    # glibc in the image.
     queue_files /lib64/liblustreapi.so
 
-    # FIXME: This is done to remove libmpi from the image before injecting
-    # from the host to workaround paraview linking to the original libmpi
-    image_libmpi=$("${ch_bin}/ch-run" "$image" -- /sbin/ldconfig -p \
-                   | grep -m 1 libmpi.so \
-                   | sed 's/.*> //' )    
-    debug " rm -f $(readlink -f "$image/$image_libmpi")"
-    # Not using queue_unlink as that prepends the image location
-    rm -f "$(readlink -f "$image/$image_libmpi")"
+    # Remove libmpi.so* from image. This works around ParaView
+    # dlopen(3)-related errors that we don't understand.
+    image_libmpis=$(  "${ch_bin}/ch-run" "$image" -- /sbin/ldconfig -p \
+                    | sed -nr 's|^.* => (/.*/libmpi\.so([0-9.]+)?)$|\1|p')
+    [ "$image_libmpis" ] || fatal "can't find libmpi.so* in image"
+    for f in $image_libmpis; do
+        queue_unlink "$f"
+        queue_unlink "$("${ch_bin}/ch-run" "$image" -- readlink -f "$f")"
+    done
 fi
 
 if [ $cray_mpi ]; then
-    # Setup files/directories required for MPI on Cray platform
-
     # ALPS libraries require the contents of this directory to be present at
     # the same path as the host. Create the mount point here, then ch-run
     # bind-mounts it later.
     queue_mkdir /var/opt/cray/alps/spool
-            
+
     # libwlm_detect.so requires this file to be present.
     queue_mkdir /etc/opt/cray/wlm_detect
     queue_files /etc/opt/cray/wlm_detect/active_wlm /etc/opt/cray/wlm_detect
 
-    # To use uGNI a pile of hugetlbfs filesystems is required at an arbitrary path
-    # (it searched /proc/mounts). ch-run bind-mounts to here later.  
+    # uGNI needs a pile of hugetlbfs filesystems at paths that are arbitrary
+    # but in a specific order in /proc/mounts. ch-run bind-mounts here later.
     queue_mkdir /var/opt/cray/hugetlbfs
 fi
 
@@ -407,13 +407,6 @@ if [ $cray_mpich ]; then
     debug "fixing soname on libmpi.so.12"
     "${ch_bin}/ch-run" -w "$image" -- \
         patchelf --set-soname libmpi.so.12 "$lib_dest/libmpi.so.12"
-fi
-
-if [ $cray_openmpi ]; then
-    # Restore libmpi.so symlink
-    debug "ln -s $(readlink "$MPIHOME/lib/libmpi.so") ${image}${lib_dest}/libmpi.so"
-        [ -f "$MPIHOME/lib/libmpi.so" ] ||
-    ln -s "$(readlink "$MPIHOME/lib/libmpi.so")" "${image}${lib_dest}/libmpi.so"
 fi
 
 if [ $lib_found ] && [ -z "$no_ldconfig" ]; then
