revert default binds; add ldconfig cache check; update test

diff --git a/bin/ch-fromhost b/bin/ch-fromhost
--- a/bin/ch-fromhost
+++ b/bin/ch-fromhost
@@ -177,10 +177,10 @@ queue_ofi_dso () {
     # Directory of OFI provider dsos (*-fi.so's).
     if [ -d "$1" ]; then
        debug "searching $1 for ofi providers"
-       for f in "${1}/"*-fi.so; do
-           queue_ofi_dso "$f"
+       for f in "$(find "$1" -maxdepth 1 -name '*-fi.so')"; do
+           [[ -z "$f" ]] || queue_ofi_dso "$f"
        done
-       [ -n "$ofi_found" ] || "no ofi providers found in $1"
+       [ -n "$ofi_found" ] || fatal "no loadable ofi provider(s) in $1"
     # Single OFI dso provider.
     elif is_ofi "$1"; then
         debug_indent "found $1"
@@ -445,7 +445,7 @@ if [ $ofi_found ]; then
     # add ofi dso provider ld library dirs.
     for c in $ld_conf; do
         debug_indent "echo '$c' >> ${image}/etc/ld.so.conf.d/ch-ofi.conf"
-        echo "$c" >> "$ch_conf"
+        echo "$c" >> "${image}/etc/ld.so.conf.d/ch-ofi.conf"
     done
 fi
 
@@ -503,6 +503,14 @@ if [ -z "$no_ldconfig" ] && { [ $lib_found ] || [ $ofi_found ] ;} then
     debug "running ldconfig"
     debug_indent "${ch_bin}/ch-run -w $image -- /sbin/ldconfig"
     "${ch_bin}/ch-run" -w "$image" -- /sbin/ldconfig
+    if [[ -n "$ofi_found" ]]; then
+        debug "validating ldconfig cache"
+        for l in $ld_conf; do
+            debug_indent "${ch_bin}/ch-run $image -- /sbin/ldconfig -p | grep -F $l > /dev/null 2>&1"
+               "${ch_bin}/ch-run" "$image" -- /sbin/ldconfig -p | grep -F "$l" > /dev/null 2>&1 \
+            || fatal "injection failed: ldconfig missing $l"
+        done
+    fi
 else
     debug "not running ldconfig"
 fi
