tidy line length

diff --git a/bin/ch-fromhost b/bin/ch-fromhost
--- a/bin/ch-fromhost
+++ b/bin/ch-fromhost
@@ -4,10 +4,10 @@
 # source:destination pairs separated by newlines, then walk through them and
 # copy them into the image.
 #
-# The colon separator is to avoid the difficulty of iterating through a sequence
-# of pairs with no arrays or structures in POSIX sh. We could avoid it by
-# taking action immediately upon encountering each file in the argument list,
-# but that would (a) yield a half-injected image for basic errors like
+# The colon separator is to avoid the difficulty of iterating through a
+# sequence of pairs with no arrays or structures in POSIX sh. We could avoid
+# it by taking action immediately upon encountering each file in the argument
+# list, but that would (a) yield a half-injected image for basic errors like
 # misspellings on the command line and (b) would require the image to be first
 # on the command line, which seems awkward.
 #
@@ -155,7 +155,8 @@ enqueue_file () {
                     ld=$(dirname "$(readlink -f "$l")")
                     # Avoid duplicates and host libfabric.so.
                     if     [ "$(echo "$ld_conf" | grep -c "$ld")" -eq 0 ] \
-                        && [ "$(echo "$ld" | grep -c "libfabric.so")" -eq 0 ]; then
+                        && [ "$(echo "$ld" | grep -c "libfabric.so")" -eq 0 ]; \
+                           then
                         enqueue_ldconf "$ld"
                     fi
                 done
@@ -303,8 +304,8 @@ if [ -n "$cray_fi_found" ]; then
     img_libfabric_path=$(echo "$img_libfabric" | sed "s@$image@@")
     cray_fi_dest=$(dirname "/$img_libfabric_path")
 
-    # Since cray's libfabric isn't a standard provider, to use slingshot we must
-    # also add any missing linked libraries from the host.
+    # Since cray's libfabric isn't a standard provider, to use slingshot we
+    # must also add any missing linked libraries from the host.
     VERBOSE "adding cray libfabric libraries"
     ldds=$(ldd "$host_libfabric" 2>&1 | grep lib | awk '{print $3}' | sort -u)
     for l in $ldds; do
@@ -352,14 +353,13 @@ if [ -n "$fi_prov_found" ]; then
     # The libfabric provider can be specified with FI_PROVIDER. The path the
     # search for shared providers at can be specified with FI_PROVIDER_PATH
     # (undocumented). This complicates the inferred destination because these
-    # variables can be inherited from the host or explicitly set in the image's
-    # /ch/environment
-    # file.
+    # variables can be inherited from the host or explicitly set in the
+    # image's /ch/environment file.
     #
     # For simplicity, the inferred injection destination is the always the
-    # 'libfabric' directory at the path where libfabric.so is found. If it does
-    # not exist, create it. Warn if FI_PROVIDER_PATH or FI_PROVIDER is found
-    # in the the image's /ch/environment file.
+    # 'libfabric' directory at the path where libfabric.so is found. If it
+    # does not exist, create it. Warn if FI_PROVIDER_PATH or FI_PROVIDER is
+    # found in the the image's /ch/environment file.
     VERBOSE "searching ${image} for libfabric shared provider destination"
     ch_env_p=$(grep -E '^FI_PROVIDER_PATH=' "${image}/ch/environment") \
              || true # avoid -e exit
@@ -395,22 +395,22 @@ if [ -f /etc/opt/cray/release/cle-release ]; then
     queue_mkdir /var/lib/hugetlbfs
     # UGNI
     if [ ! -L /etc/opt/cray/release/cle-release ]; then
-        # ALPS libraries require the contents of this directory to be present at
-        # the same path as the host. Create the mount point here, then ch-run
-        # bind-mounts it later.
+        # ALPS libraries require the contents of this directory to be present
+        # at the same path as the host. Create the mount point here, then
+        # ch-run bind-mounts it later.
         queue_mkdir /var/opt/cray/alps/spool
 
-        # The cray-ugni provider will link against cray's libwlm_detect so. Create
-        # the mount point for ch-run.
+        # The cray-ugni provider will link against cray’s libwlm_detect so.
+        # Create the mount point for ch-run.
         queue_mkdir /opt/cray/wlm_detect
 
-        # libwlm_detect.so requires file(s) to present at the same path as the host.
-        # Create mount point for ch-run.
+        # libwlm_detect.so requires file(s) to present at the same path as the
+        # host. Create mount point for ch-run.
         queue_mkdir /etc/opt/cray/wlm_detect
 
-        # OFI uGNI provider, libgnix-fi.so, links against the Cray host's
-        # libxpmem, libudreg, libalpsutil, libalpslli, and libugni; create mount
-        # points for ch-run to use later.
+        # OFI uGNI provider, libgnix-fi.so, links against the Cray host’s
+        # libxpmem, libudreg, libalpsutil, libalpslli, and libugni; create
+        # mount points for ch-run to use later.
         queue_mkdir /opt/cray/udreg
         queue_mkdir /opt/cray/xpmem
         queue_mkdir /opt/cray/ugni
@@ -418,9 +418,9 @@ if [ -f /etc/opt/cray/release/cle-release ]; then
     fi
     # CXI (slingshot)
     if [ -f /opt/cray/etc/release/cos ]; then
-        # Newer Cray Shasta environments require the contents of this directory
-        # to be present at the same path as the host. Create mount points for
-        # ch-run to use later.
+        # Newer Cray Shasta environments require the contents of this
+        # directory to be present at the same path as the host. Create mount
+        # points for ch-run to use later.
         queue_mkdir /var/spool/slurmd
     fi
 fi
@@ -450,7 +450,8 @@ if [ "$fi_prov_found" ] || [ "$cray_fi_found" ]; then
         DEBUG "creating empty ld.so.conf"
         touch "${image}/etc/ld.so.conf"
     fi
-    if ! grep -F 'include ld.so.conf.d/*.conf' "${image}/etc/ld.so.conf" > /dev/null 2>&1; then
+    if !   grep -F 'include ld.so.conf.d/*.conf' "${image}/etc/ld.so.conf" \
+         > /dev/null 2>&1; then
         DEBUG "ld.so.conf: adding 'include ld.so.conf.d/*.conf'"
         echo 'include ld.so.conf.d/*.conf' >> "${image}/etc/ld.so.conf"
     fi
@@ -458,7 +459,7 @@ if [ "$fi_prov_found" ] || [ "$cray_fi_found" ]; then
     printf '' > "${image}/etc/ld.so.conf.d/ch-ofi.conf"
     # add ofi dso provider ld library dirs.
     for c in $ld_conf; do
-        DEBUG "ld.so.conf: adding %{c}"
+        DEBUG "ld.so.conf: adding ${c}"
         echo "$c" >> "${image}/etc/ld.so.conf.d/ch-ofi.conf"
     done
 fi
@@ -477,13 +478,13 @@ for file in $inject_files; do
             if ldd "$f" | grep libcxi > /dev/null 2>&1; then
                 d=$cray_fi_dest
             fi
-        ;;
+            ;;
         *-fi.so)
             d=$fi_prov_dest
-        ;;
+            ;;
         *)
             d=$lib_dest
-        ;;
+            ;;
         esac
         infer=" (inferred)"
     fi
@@ -504,21 +505,25 @@ done
 IFS="$old_ifs"
 
 if       [ -z "$no_ldconfig" ] \
-    && { [ "$lib_found" ] || [ "$fi_prov_found" ] || [ "$cray_fi_found" ] ;} then
+    && {    [ "$lib_found" ] \
+         || [ "$fi_prov_found" ] \
+         || [ "$cray_fi_found" ] ;} then
     VERBOSE "running ldconfig"
-    "${ch_bin}/ch-run" -w "$image" -- /sbin/ldconfig 2> /dev/null || FATAL 'ldconfig error'
+    "${ch_bin}/ch-run" -w "$image" -- /sbin/ldconfig 2> /dev/null \
+        || FATAL 'ldconfig error'
     if [ -n "$fi_prov_found" ] || [ -n "$cray_fi_found" ]; then
         VERBOSE "validating ldconfig cache"
         for file in $inject_files; do
             f="$(basename "${file%%:*}")"
-            f=$("${ch_bin}/ch-run" "$image" -- find / \
-                                               -not \( -path /proc -prune \) \
-                                               -not \( -path /dev -prune \) \
-                                               -not \( -path /tmp -prune \) \
-                                               -not \( -path /sys -prune \) \
-                                               -not \( -path /var/opt/cray -prune \) \
-                                               -not \( -path /etc/opt/cray -prune \) \
-                                               -name  "$f")
+            f=$(   "${ch_bin}/ch-run" "$image" \
+                -- find / \
+                        -not \( -path /proc -prune \) \
+                        -not \( -path /dev -prune \) \
+                        -not \( -path /tmp -prune \) \
+                        -not \( -path /sys -prune \) \
+                        -not \( -path /var/opt/cray -prune \) \
+                        -not \( -path /etc/opt/cray -prune \) \
+                        -name  "$f")
             if [ "$("${ch_bin}/ch-run" "$image" -- ldd "$f" | grep -c 'not found ')" -ne 0 ]; then
                 FATAL "ldconfig: '${ch_bin}/ch-run $image -- ldd $f' failed"
             fi
