fix issues

diff --git a/bin/ch-fromhost b/bin/ch-fromhost
--- a/bin/ch-fromhost
+++ b/bin/ch-fromhost
@@ -296,7 +296,7 @@ if [ $lib_found ]; then
                 3>&1 1>&2 | grep -E '^/' | cut -d: -f1 | head -1 )
     [ -n "$lib_dest" ] || fatal 'empty path from ldconfig'
     [ -z "${lib_dest%%/*}" ] || fatal "bad path from ldconfig: ${lib_dest}"
-    debug "shared library destination: ${lib_dest}"
+    debug "shared library destination: ${image}/${lib_dest}"
 fi
 
 if [ $ofi_found ]; then
@@ -309,17 +309,20 @@ if [ $ofi_found ]; then
     #
     # If it doesn't exist we need to create it.
     debug "searching ${image} for libfabric dso provider destination..."
-    ofi_dest=$(find "$image" -name "libfabric" | grep -E '^.*lib\/libfabric$')
-    if [ -z $ofi_dest ]; then
-       debug "  valid destination not found; searching for libfabric.so"
-       ofi_so=$(find "$image" -name  "libfabric.so")
-       [ -n ofi_so ] || fatal "libfabric.so not found in $image"
-       debug "  found: $ofi_so"
-       ofi_dest=$(dirname $ofi_so)
-       queue_mkdir "$ofi_dest"
-    else
-        debug "  found: $ofi_dest"
-    fi
+    ofi_so=$("${ch_bin}/ch-run" --no-home "$image" -- find / \
+                                                -not \( -path /proc -prune \) \
+                                                -not \( -path /dev -prune \) \
+                                                -not \( -path /tmp -prune \) \
+                                                -not \( -path /sys -prune \) \
+                                                -not \( -path /var/opt/cray -prune \) \
+                                                -not \( -path /etc/opt/cray -prune \) \
+                                                -not \( -path /opt/cray -prune \) \
+                                                -name  "libfabric.so")
+    [ -n ofi_so ] || fatal "libfabric.so not found in $image"
+    debug "  found: $image/$ofi_so"
+    ofi_dest=$(dirname $ofi_so)
+    ofi_dest="${ofi_dest}/libfabric"
+    queue_mkdir "$ofi_dest"
     debug "using libfabric dso provider destination: $ofi_dest"
     lib_found=yes
 fi
@@ -416,15 +419,15 @@ for file in $inject_ofi; do
     debug "  ${f} -> ${d}${infer}"
     [ "$d" ] || fatal "no destination for: ${f}"
     [ -z "${d%%/*}" ] || fatal "not an absolute path: ${d}"
-    [ -d "${d}" ] || fatal "not a directory: ${d}"
-    if [ ! -w "${d}" ]; then
+    [ -d "${image}/${d}" ] || fatal "not a directory: ${image}/${d}"
+    if [ ! -w "${image}${d}" ]; then
         # Some images unpack with unwriteable directories; fix. This seems
         # like a bit of a kludge to me, so I'd like to remove this special
         # case in the future if possible. (#323)
-        info "${d} not writeable; fixing"
-        chmod u+w "${d}" || fatal "can't chmod u+w: ${d}"
+        info "${image}${d} not writeable; fixing"
+        chmod u+w "${image}${d}" || fatal "can't chmod u+w: ${image}${d}"
     fi
-       cp --dereference --preserve=all "$f" "${d}/" \
+       cp --dereference --preserve=all "$f" "${image}${d}/" \
     || fatal "cannot inject: ${f}"
 
 done
