move rootemu to full scope

diff --git a/bin/ch-test b/bin/ch-test
--- a/bin/ch-test
+++ b/bin/ch-test
@@ -1221,6 +1221,10 @@ case $phase in
         done
         ;;
     rootemu)
+        if [[ $scope != full ]]; then
+            printf "error: rootemu incompatible with scope: $scope\n"
+            exit 1
+        fi
         test_rootemu "foo"
         ;;
     run)
