update ch-test

diff --git a/bin/ch-test b/bin/ch-test
--- a/bin/ch-test
+++ b/bin/ch-test
@@ -1,122 +1,8 @@
 #!/bin/bash
 
-check_builder () {
-    case $CH_BUILDER in
-    ch-grow)
-        printf "checking builder (ch-grow) sanity...\n"
-        if (! command -v umoci &> /dev/null); then
-            fatal 'builder: ch-grow: missing umoci'
-        fi
-        if (! command -v skopeo &> /dev/null); then
-            fatal 'builder: ch-grow: missing skopeo'
-        fi
-        if (! command -v python3 &> /dev/null); then
-            fatal 'builder: ch-grow: missing python3'
-        fi
-        if (! python3 -c "import lark" &> /dev/null); then
-            fatal "builder: ch-grow: missing python3 module 'lark-parser'"
-        fi
-        ;;
-    buildah)
-        # TODO: determine how to handle all the various ch-build buildah cases,
-        # e.g., buildah, buildah-runc, buildah-setuid
-        echo "checking builder (buildah) sanity..."
-        v_buildah=$(buildah --version | cut -d ' ' -f3)
-        if [[ -z $v_buildah ]]; then
-            fatal 'builder: buildah: not installed'
-        fi
-        b_major=$(echo "$v_buildah" | cut -d '.' -f1)
-        b_minor=$(echo "$v_buildah" | cut -d '.' -f2)
-        b_build=$(echo "$v_buildah" | cut -d '.' -f3)
-        if [[ $b_major -lt  1 ]] \
-        || [[ $b_minor -lt 11 ]] \
-        || [[ $b_build -lt  2 ]]; then
-            fatal 'builder: buildah: version must be 1.11.2 or greater'
-        fi
-        if (buildah rm "ch-test_$version" &> /dev/null); then
-            echo "removing test container ch-test_$version"
-        fi
-        if (! buildah from --name "ch-test_$version" scratch &> /dev/null); then
-            fatal 'builder: buildah: sanity check failed (is buildah working?)'
-        fi
-        if (! buildah containers | awk '{print $4}' | \
-              grep -w "ch-test_$version" &> /dev/null); then
-                  fatal 'builder: buildah: sanity check failed (is buildah working?)'
-        fi
-        ;;
-    docker)
-        echo "checking builder (docker) sanity..."
-        if (! command -v docker &> /dev/null); then
-            fatal 'builder: docker: not installed'
-        fi
-        if (! docker run hello-world &> /dev/null); then
-            fatal 'builder: docker: run hello failed'
-        fi
-        ;;
-    *)
-        fatal "builder: $CH_BUILDER: not supported"
-    esac
-}
-
-fatal () {
-    printf 'fatal: %s\n\n' "$1" 1>&2
-    exit 1
-}
-
-perm_dirs () {
-    printf '\nfile permission enforcement tests:\n'
-    if [[ $CH_TEST_PERMDIRS == 'skip' ]] || [[ -n $CH_TEST_DONT_SUDO ]] || (! sudo -v &> /dev/null); then
-        printf 'skipping file permission tests...\n'
-        return 0
-    fi
-    # shellcheck disable=SC2068
-    for d in ${CH_TEST_PERMDIRS[@]}; do
-        if [[ -d "${d}/perms_test" ]]; then
-            printf "%s/perms_test exists (consider removing; later tests may fail). \n" "$d"
-            continue
-        else
-            sudo ./make-perms-test "$d" "$USER" nobody
-        fi
-    done
-    echo
-}
-
-print_dry () {
-    if [[ $phase == clean ]]; then
-        echo "rm -rf $CH_TEST_TARDIR"
-        echo "rm -rf $CH_TEST_IMGDIR"
-        if [[ ! $CH_TEST_PERMDIRS == skip ]]; then
-            # shellcheck disable=SC2068
-            for d in ${CH_TEST_PERMDIRS[@]}; do
-                printf 'rm -rf %s/perms_test\n' "${d}"
-            done
-        fi
-    else
-        if [[ ! $phase == run ]]; then
-            printf 'file permission enforcement tests:\n'
-            # shellcheck disable=SC2068
-            for d in ${CH_TEST_PERMDIRS[@]}; do
-                printf 'sudo ./make-perms-test %s %s nobody\n' "$d" "$USER"
-            done
-            echo
-        fi
-        case $phase in
-        build) echo "make test-build";;
-        run)   echo "make test-run";;
-        all)   echo "make test";;
-        esac
-    fi
-    exit 0
-}
-
-libexec="$(cd "$(dirname "$0")" && pwd)"
+libexec="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 . "${libexec}/base.sh"
 . "${libexec}/version.sh"
-
-
-bin_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-top_dir=${bin_dir%/*}
-version=$("${bin_dir}/ch-run" --version 2>&1)
 
 # shellcheck disable=SC2034
 usage=$(cat <<EOF
@@ -124,32 +10,148 @@ Run the Charliecloud test suite.
 
 Usage:
 
-  $ $(basename "$0") [ARGS ...] PHASE
+  $ $(basename "$0") [PHASE] [OPTIONS]
 EOF
 )
 
-parse_basic_args "$@"
+check_builder () {
+    printf "\nchecking builder: "
+    case $CH_BUILDER in
+    ch-grow)
+        if ! ("${ch_bin}/ch-grow" --dependencies); then
+            fatal 'builder: ch-grow: missing dependencies'
+        fi
+        bl=$(readlink -f "$ch_bin"/ch-grow)
+        bv=$("$bl" --version)
+        ;;
+    buildah)
+        ;&
+    buildah-runc)
+        ;&
+    buildah-setuid)
+        if (! command -v buildah &> /dev/null); then
+            fatal 'builder: buildah: not installed.'
+        fi
+        bl=$(command -v buildah)
+        bv=$(buildah --version | awk '{print $3}')
+        min='1.11.2'
+        ;;
+    docker)
+        if (! command -v docker &> /dev/null); then
+            fatal 'builder: docker: not installed'
+        fi
+        bl=$(command -v docker)
+        bv=$(docker --version | awk '{print $3}' | sed -e 's/,//')
+        ;;
+    *)
+        fatal "builder: $CH_BUILDER: not supported"
+        ;;
+    esac
+    printf '%s %s: OK\n\n' "$bl" "$bv"
+    check_min_ver 'builder' "$min" "$bv"
+}
 
-if [ "$#" -lt 1 ]; then
-    usage
-    exit 0
+check_min_ver () {
+    if [[ $(printf '%s\n%s\n' "$2" "$3" | sort -V | head -n1) != "$2" ]]; then
+        fatal "$1: mininum version $2"
+    fi
+}
+
+check_scope () {
+    case $1 in
+    quick|standard|full)
+        return 0
+        ;;
+    *)
+        fatal "scope: invalid: $1"
+        ;;
+    esac
+}
+
+check_tardir () {
+    printf '\nchecking tarball directory: %s: ' "$CH_TEST_TARDIR"
+    # The run phase requires artifacts from a successful build phase. Thus,
+    # we check sanity based on the minimal set of artifacts (quick scope).
+    check_tardir_file alpine39{.tar.gz,.sqfs,.pq_missing}
+    check_tardir_file alpine39_dp{.tar.gz,.sqfs,.pq_missing}
+    check_tardir_file chtest{.tar.gz,.sqfs,.pq_missing}
+    printf 'OK\n'
+}
+
+check_tardir_file () {
+    local missing
+    for f in "$@"; do
+        if [[ -f ${CH_TEST_TARDIR}/${f} ]]; then
+            return 0
+        else
+            missing+=("${CH_TEST_TARDIR}/${f}")
+        fi
+    done
+    fatal "phase: $phase: missing build phase artifact(s): ${missing[*]}"
+}
+
+fatal () {
+    printf 'error: %s\n\n' "$1" 1>&2
+    exit 1
+}
+
+# Create test directories for TAR and IMG. This is to avoid cryptic bats error
+# (#347) that occurs when setting a CH_TEST_IMGDIR or CH_TEST_TARDIR variables
+# to a path where there are two or more subdirectories that do not exist.
+mk_dirs () {
+if [[ ! -d $CH_TEST_TARDIR ]]; then
+    echo "creating $CH_TEST_TARDIR"
+    mkdir -p "$CH_TEST_TARDIR"
 fi
+if [[ ! -d $CH_TEST_IMGDIR ]]; then
+    echo "creating $CH_TEST_IMGDIR"
+    mkdir -p "$CH_TEST_IMGDIR"
+fi
+}
+
+# Remove CH_TEST_PERMDIRS directories. Ensure that the target directory has
+# only two sub directories, e.g., nopass and pass.
+rm_ () {
+    if [[ $(find "${d}" -maxdepth 1 -mindepth 1 | wc -l) == 2 ]] && \
+       (find "${d}" -maxdepth 1 -mindepth 1 -name pass -type d) && \
+       (find "${d}" -maxdepth 1 -mindepth 1 -name nopass -type d); then
+        echo "removing ${d}"
+        sudo rm -rf --one-file-system "$d"
+    fi
+}
+
+single_assignment () {
+    if [[ -n $1 ]]; then
+        fatal "phase: assignment more than once (originally set to: $phase)"
+    fi
+}
+
+set_builder () {
+    if [[ -n $builder ]]; then
+        export CH_BUILDER=$builder
+        method='command line'
+    elif [[ -n $CH_BUILDER ]]; then
+        method='environment variable'
+    else
+        builder_choose
+        method='default'
+    fi
+    printf 'setting builder to %s (%s)\n' "$CH_BUILDER" "$method"
+    if [[ $CH_BUILDER == 'ch-grow' ]]; then
+        set_chvar CH_GROW_STORAGE 'ch-grow storage' '' "$CH_GROW_STORAGE" /var/tmp/ch-grow_
+    fi
+}
+
+top_dir=$(readlink -f "${ch_bin%/*}")
 
 # Ensure ch-run has been compiled (issue #329).
-if (! "${bin_dir}/ch-run" --version &> /dev/null); then
-    fatal 'ch-run not found (did you build with make?)'
+if (! "${ch_bin}/ch-run" --version &> /dev/null); then
+    fatal "ch-run not found; expected in $ch_bin."
 fi
 
 # Ensure namespaces are configured properly.
-if (! "${bin_dir}/ch-checkns" &> /dev/null); then
-    fatal 'namespace sanity check (ch-checkns) failed'
-fi
-
-# Ensure bats is installed.
-if (! bats --version &> /dev/null); then
-    if (! "${top_dir}/test/bats/bin/bats" --version &> /dev/null); then
-        fatal 'dependency: bats is not installed'
-    fi
+if (! "${ch_bin}/ch-checkns" &> /dev/null); then
+    fatal 'namespace sanity check (ch-checkns) failed.'
 fi
 
 # Ensure we have bash 4.1 or higher
@@ -159,148 +161,162 @@ if (bash -c 'set -e; [[ 1 = 0 ]]; exit 0'); then
     fatal 'dependency: bash: need at least Bash 4.1 for these tests.'
 fi
 
-# Ensure BATS_TMPDIR is set to /tmp (issue #278)
+# Ensure BATS_TMPDIR is set to /tmp (issue #278).
 if [[ -n $BATS_TMPDIR ]]; then
-    if [[ ! $BATS_TMPDIR == /tmp ]]; then
-        echo "setting BATS_TMPDIR=/tmp (was $BATS_TMPDIR; issue #278)"
-        export BATS_TMPDIR=/tmp
+    if [[ ! $BATS_TMPDIR == '/tmp/'* ]]; then
+        fatal "env: BATS_TMPDIR: not set to /tmp (issue #278)."
     fi
 fi
 
-# Determine local vs prefix test installation.
+# Determine source vs prefix installation.
 if [[ -d "${top_dir}/test" ]]; then
-    # local install
+    # source install
     testdir=${top_dir}/test
 else
     # prefix installation
-    testdir=${top_dir%/charliecloud}/libexec/charliecloud-${version}/test
+    testdir=${top_dir%/charliecloud}/libexec/charliecloud-$(version 2>&1)/test
 fi
 
-# Check for test directory
-if [[ ! -d $testdir ]]; then
-    fatal "Unable to locate the Charliecloud test suite"
+# Check for test directory.
+if (! cd "$testdir"); then
+    fatal "test directory not found; expected in $top_dir"
 fi
 
-cd "$testdir" || fatal 'cannot cd into the test directory'
+cd "$testdir" || fatal "cd $testdir failed"
 
-# Parse arguments
+# Ensure bats is installed.
+if (command -v bats &> /dev/null); then
+    bats=$(command -v bats)
+    bv=$(bats --version)
+elif [[ -x "${test_dir}/bats/bin/bats" ]]; then
+    bats=$(readlink -f "${test_dir}/bats/bin/bats")
+    bv=$($bats --version)
+else
+    fatal 'dependency: bats is not installed.'
+fi
+
+# Parse arguments.
 while [[ $# -gt 0 ]]; do
     opt=$1; shift
     case $opt in
-    build|run|examples|all|clean)
-        [[ -z $phase ]] || fatal 'phase: can only assign once'
+    build|clean|examples|mk-perm-dirs|rm-perm-dirs|run)
+        single_assignment "$phase"
         phase=$opt
         ;;
     -b|--builder)
-        [[ -z $builder ]] || fatal 'builder: can only assign once'
-        export CH_BUILDER=$1; shift
-        ;;
-    -p|--prefix)
-        [[ -z $prefix ]] || fatal 'prefix: can only assign once'
-        export CH_TEST_IMGDIR="${1}/img"
-        export CH_TEST_TARDIR="${1}/tar"
-        export CH_TEST_PERMDIRS=$1
-        shift
-        ;;
-    -s|--scope)
-        [[ -z $scope ]] || fatal 'scope: can only assign once'
-        export CH_TEST_SCOPE=$1; shift
-        ;;
-    --no-sudo)
-        no_sudo=true
-        export CH_TEST_DONT_SUDO=yes
+        single_assignment "$builder"
+        builder=$1; shift
         ;;
     --dry-run)
         dry=true
         ;;
+    -h|--help)
+        usage 0
+        ;;
+    --img-dir)
+        single_assignment "$imgdir"
+        imgdir=$1; shift
+        ;;
+    --perm-dir)
+        permdirs+=("$1"); shift
+        ;;
+    -s|--scope)
+        single_assignment "$scope"
+        check_scope "$1"
+        scope=$1; shift
+        ;;
+    --sudo)
+        use_sudo=yes
+        ;;
+    --tar-dir)
+        single_assignment "$tardir"
+        tardir=$1; shift
+        ;;
+    --version)
+        version; exit 0
+        ;;
     *)
         fatal "unrecognized argument: $opt"
+        ;;
     esac
 done
 
 if [[ -z $phase ]]; then
-    fatal 'test phase not specified'
+    phase=all
+    printf "executing test phases: build, run, and examples\n"
 fi
 
-if [[ -n $no_sudo ]]; then
-    export CH_TEST_PERMDIRS=skip
+printf 'using ch-run %s at %s\n' "$(version 2>&1)" "${ch_bin}/ch-run"
+printf 'using bats %s at %s\n' "$(echo "$bv" | awk '{print $2}')" "$bats"
+printf 'using test directory %s\n' "$testdir"
+
+#           variable name     description           command line        environment         default
+set_chvar   CH_TEST_SCOPE     'test scope'          "$scope"            "$CH_TEST_SCOPE"    standard
+set_chvar   CH_TEST_SUDO      'sudo capabilities'   "$use_sudo"         "$CH_TEST_SUDO"     no
+set_chvar   CH_TEST_IMGDIR    'image directory'     "$imgdir"           "$CH_TEST_IMGDIR"   /var/tmp/img
+set_chvar   CH_TEST_TARDIR    'tarball directory'   "$tardir"           "$CH_TEST_TARDIR"   /var/tmp/tar
+set_chvar   CH_TEST_PERMDIRS  'permission fixtures' "${permdirs[*]}"    "$CH_TEST_PERMDIRS" skip
+set_builder
+
+if   [[ $phase == 'mk-perm-dirs' ]] && [[ -z $use_sudo ]]; then
+    fatal "phase: $phase: requires --sudo"
+elif [[ $phase == *'perm'* ]] && [[ ${CH_TEST_PERMDIRS[*]} == skip ]]; then
+    fatal "phase: $phase: CH_TEST_PERMDIRS: can't be 'skip'"
 fi
 
-# Use defaults if variables are not set.
-export CH_TEST_TARDIR=${CH_TEST_TARDIR:-/var/tmp/tar}
-export CH_TEST_IMGDIR=${CH_TEST_IMGDIR:-/var/tmp/img}
-export CH_TEST_PERMDIRS=${CH_TEST_PERMDIRS:-'/var/tmp /tmp'}
-export CH_TEST_SCOPE=${CH_TEST_SCOPE:-standard}
-export CH_BUILDER=${CH_BUILDER:-ch-grow}
-export CH_GROW_STORAGE=${CH_GROW_STORAGE:-/var/tmp/ch-grow}
+case $phase in
+    all)
+        ;&
+    build)
+        check_builder
+        ;;
+    run)
+        check_tardir
+        ;;
+esac
 
-if [[ -z $CH_TEST_DONT_SUDO ]]; then
-    printf '\n%s\t%s\n' CH_TEST_DONT_SUDO "(is empty)"
-else
-    printf '\n%s\t%s\n' CH_TEST_DONT_SUDO "(is set)"
-fi
-printf '%s\t\t%s\n'   CH_TEST_TARDIR    "$CH_TEST_TARDIR"
-printf '%s\t\t%s\n'   CH_TEST_IMGDIR    "$CH_TEST_IMGDIR"
-printf '%s\t%s\n'     CH_TEST_PERMDIRS  "$CH_TEST_PERMDIRS"
-printf '%s\t\t%s\n'   CH_TEST_SCOPE     "$CH_TEST_SCOPE"
-printf '%s\t\t%s\n'   CH_BUILDER        "$CH_BUILDER"
-if [[ $CH_BUILDER == 'ch-grow' ]]; then
-    printf '%s\t\t%s\n' CH_GROW_STORAGE   "$CH_GROW_STORAGE"
-fi
-printf '\ntest root directory:\t%s\n\n' "$testdir"
-
-if [[ -n $dry ]]; then
-    print_dry
-fi
-
-# Create test directories for TAR and IMG. This is to avoid cryptic bats error
-# (#347) that occurs when setting a CH_TEST_IMGDIR or CH_TEST_TARDIR variables
-# to a path where there are two or more subdirectories that do not exist.
-if [[ ! -d $CH_TEST_TARDIR ]]; then
-     mkdir -p "$CH_TEST_TARDIR"
-fi
-if [[ ! -d $CH_TEST_IMGDIR ]]; then
-    mkdir -p "$CH_TEST_IMGDIR"
+if [[ -n $dry ]];then
+    printf "exiting; dry-run complete"
+    exit 0
 fi
 
 # Execute phase
 case $phase in
     build)
-        check_builder
-        perm_dirs
+        mk_dirs
         make test-build
-    ;;
+        ;;
     run)
         make test-run
-    ;;
+        ;;
     examples)
         make test-test
-    ;;
+        ;;
     all)
-        check_builder
-        perm_dirs
+        mk_dirs
         make test
-    ;;
+        ;;
+    mk-perm-dirs)
+        printf '\ngenerating file permission enforcement test fixtures:\n'
+        for d in $CH_TEST_PERMDIRS; do
+            if [[ -d ${d} ]]; then
+                printf '%s already exists\n' "$d"
+                continue
+            else
+                sudo "${testdir}/make-perms-test" "$d" "$USER" nobody
+            fi
+        done
+        echo
+        ;;
+    rm-perm-dirs)
+        for d in $CH_TEST_PERMDIRS; do
+            rm_ "$d"
+        done
+        ;;
     clean)
-        echo "removing $CH_TEST_TARDIR..."
-        echo "removing $CH_TEST_IMGDIR..."
-        rm -rf "$CH_TEST_TARDIR"
-        rm -rf "$CH_TEST_IMGDIR"
-
-        if [[ $CH_TEST_PERMDIRS == 'skip' ]]; then
-            echo "phase: clean: CH_TEST_PERMDIRS set to 'skip' (skipping)"
-        elif [[ -n $CH_TEST_DONT_SUDO ]]; then
-            echo "phase: clean: CH_TEST_DONT_SUDO is set (skipping)"
-        elif (! sudo -v &> /dev/null); then
-            echo "phase: clean: you don't appear to have sudo for CH_TEST_PERMDIRS removal (skipping)"
-        else
-            # shellcheck disable=SC2068
-            for f in ${CH_TEST_PERMDIRS[@]}; do
-                if [[ -d "${f}/perms_test" ]]; then
-                    echo "removing ${f}/perms_test..."
-                    sudo rm -rf "${f}/perms_test"
-                fi
-            done
-        fi
-    ;;
+        echo "removing $CH_TEST_TARDIR"
+        rm -rf --one-file-system "$CH_TEST_TARDIR"
+        echo "removing $CH_TEST_IMGDIR"
+        rm -rf --one-file-system "$CH_TEST_IMGDIR"
+        ;;
 esac
