PR #704 from me: ch-test: add --file (closes #607)

diff --git a/bin/ch-test b/bin/ch-test
--- a/bin/ch-test
+++ b/bin/ch-test
@@ -1,8 +1,12 @@
 #!/bin/bash
 
-set -e
+### Setup we need right away
 
+set -e
 export LC_ALL=C  # predictable sorting
+
+
+### Functions we need right away
 
 fatal () {
     printf 'error: %s\n' "$1" 1>&2
@@ -13,13 +17,15 @@ warning () {
     printf 'warning: %s\n' "$1" 1>&2
 }
 
+
+### Setup
+
 lib=$(cd "$(dirname "$0")" && pwd)/../lib/charliecloud
 if [[ ! -f ${lib}/base.sh ]]; then
     fatal "install or build problem: not found: ${lib}/base.sh"
 fi
 . "${lib}/base.sh"
 . "${lib}/contributors.bash"
-
 export ch_bin
 
 # shellcheck disable=SC2034
@@ -49,6 +55,9 @@ Additional options:
 See the man page for important details.
 EOF
 )
+
+
+### Functions
 
 builder_check () {
     printf 'checking builder ...\n'
@@ -189,14 +198,28 @@ dirs_unpriv_rm () {
     dir_tmp_rm
 }
 
-pq_missing () {
-    if [[ $phase == all || $phase == build ]]; then
-        local img=$1
-        local out=$2
-        local tag
-        tag=$(test_make_auto tag "$img")
-        printf '%s\n' "$out" >> "${CH_TEST_TARDIR}/${tag}.pq_missing"
+pack_fmt_set () {
+    width=$1
+    if [[ -n $pack_fmt ]]; then
+        case $pack_fmt in
+        '🐘')  # elephant emoji
+            pack_fmt=squash
+            ;;
+        '📠')  # fax machine emoji
+            pack_fmt=tar
+            ;;
+        esac
+        export CH_PACK_FMT=$pack_fmt
+        method='command line'
+    elif [[ -n $CH_PACK_FMT ]]; then
+        method='environment'
+    else
+        pack_fmt_choose
+        method='default'
     fi
+    printf "%-*s %s (%s)\n" \
+           "$width" 'packed image format:' "$CH_PACK_FMT" "$method"
+    pack_fmt_valid "$CH_PACK_FMT"
 }
 
 pedantry_set () {
@@ -223,6 +246,16 @@ pedantry_set () {
         use_sudo_default=yes
     else
         use_sudo_default=
+    fi
+}
+
+pq_missing () {
+    if [[ $phase == all || $phase == build ]]; then
+        local img=$1
+        local out=$2
+        local tag
+        tag=$(test_make_auto tag "$img")
+        printf '%s\n' "$out" >> "${CH_TEST_TARDIR}/${tag}.pq_missing"
     fi
 }
 
@@ -272,7 +305,7 @@ test_build () {
     if [[ ! -f ${TMP_}/build_auto.bats ]]; then
         fatal "${TMP_}/build_auto.bats not found"
     fi
-    bats build.bats "${TMP_}/build_auto.bats" build_post.bats
+    bats "${TMP_}/build_auto.bats" build/*.bats
 }
 
 test_examples () {
@@ -284,26 +317,6 @@ test_examples () {
     if (find "$TMP_" -name '*_example.bats' | grep -q .); then
         bats "${TMP_}"/*_example.bats
     fi
-}
-
-test_run () {
-    echo 'executing run phase tests ...'
-    if [[ ! -f ${TMP_}/run_auto.bats ]]; then
-        fatal "${TMP_}/run_auto.bats not found"
-    fi
-    bats run_first.bats "${TMP_}/run_auto.bats" ./run/*.bats
-    set -e
-    if [[ $CH_TEST_SCOPE != quick ]]; then
-        for guest_user in $(id -un) root nobody; do
-            for guest_group in $(id -gn) root $(id -gn nobody); do
-                export GUEST_USER=$guest_user
-                export GUEST_GROUP=$guest_group
-                echo "testing as $GUEST_USER $GUEST_GROUP"
-                bats run/ch-run_uidgid.bats
-            done
-        done
-    fi
-    set +e
 }
 
 test_make () {
@@ -360,7 +373,11 @@ test_make () {
                 bat_file=$(dirname "$i")/test.bats
                 tag=$(test_make_tag_from_path "$i")
                 cp "$bat_file" "${TMP_}/${tag}_example.bats"
-                sed -i "s/%ch_test_tag%/${tag}/g" "${TMP_}/${tag}_example.bats"
+                # Substitute $ch_test_tag here with sed because we run all the
+                # examples together later, but the value needs to vary between
+                # the files. Watch the escaping here.
+                sed -i "s/\\\$ch_test_tag/${tag}/g" \
+                       "${TMP_}/${tag}_example.bats"
                 echo "found: $(dirname "$i")"
             fi
         done
@@ -560,28 +577,36 @@ test_make_template_print () {
     return
 }
 
-pack_fmt_set () {
-    width=$1
-    if [[ -n $pack_fmt ]]; then
-        case $pack_fmt in
-        '🐘')  # elephant emoji
-            pack_fmt=squash
-            ;;
-        '📠')  # fax machine emoji
-            pack_fmt=tar
-            ;;
-        esac
-        export CH_PACK_FMT=$pack_fmt
-        method='command line'
-    elif [[ -n $CH_PACK_FMT ]]; then
-        method='environment'
-    else
-        pack_fmt_choose
-        method='default'
+test_one_file () {
+    if [[ $one_file != *.bats ]]; then
+        # Assume it's a Dockerfile or Build file; derive tag and test.bats.
+        ch_test_tag=$(test_make_tag_from_path "$one_file")
+        export ch_test_tag
+        one_file=$(dirname "$one_file")/test.bats
+        printf 'tag:   %s\n' "$ch_test_tag"
     fi
-    printf "%-*s %s (%s)\n" \
-           "$width" 'packed image format:' "$CH_PACK_FMT" "$method"
-    pack_fmt_valid "$CH_PACK_FMT"
+    printf 'file:  %s\n' "$one_file"
+    bats "$one_file"
+}
+
+test_run () {
+    echo 'executing run phase tests ...'
+    if [[ ! -f ${TMP_}/run_auto.bats ]]; then
+        fatal "${TMP_}/run_auto.bats not found"
+    fi
+    bats run_first.bats "${TMP_}/run_auto.bats" ./run/*.bats
+    set -e
+    if [[ $CH_TEST_SCOPE != quick ]]; then
+        for guest_user in $(id -un) root nobody; do
+            for guest_group in $(id -gn) root $(id -gn nobody); do
+                export GUEST_USER=$guest_user
+                export GUEST_GROUP=$guest_group
+                echo "testing as $GUEST_USER $GUEST_GROUP"
+                bats run/ch-run_uidgid.bats
+            done
+        done
+    fi
+    set +e
 }
 
 # Exit with failure if given version number is below a minimum.
@@ -602,6 +627,9 @@ version_check () {
 win () {
     printf "\nAll tests passed.\n"
 }
+
+
+### Body of script
 
 # Ensure ch-run has been compiled (issue #329).
 if (! "${ch_bin}/ch-run" --version &> /dev/null); then
@@ -701,6 +729,16 @@ while [[ $# -gt 0 ]]; do
     --dry-run)
         dry=true
         ;;
+    -f|--file)
+        require_unset phase
+        phase=one-file
+        one_file=$1; shift
+        ;;
+    --file=*)
+        require_unset phase
+        phase=one-file
+        one_file=${opt#*=}
+        ;;
     -h|--help)
         usage 0
         ;;
@@ -784,7 +822,20 @@ else
 fi
 printf 'contributor:  %s\n\n' "$ch_contributor_note"
 
+if [[ $phase = one-file ]]; then
+    if [[ ! -f $one_file ]]; then
+        fatal "not a file: $one_file"
+    fi
+    one_file=$(readlink -f "$one_file")  # make absolute b/c we cd later
+    if [[ $one_file = */test.bats ]]; then
+        fatal '--file: must specify build recipe file, not test.bats'
+    fi
+fi
+
 printf "%-21s %s" 'phase:' "$phase"
+if [[ $phase = one-file ]]; then
+    printf ': %s' "$one_file"
+fi
 if [[ -z $phase ]]; then
     phase=all
     printf 'build run examples'
@@ -878,24 +929,6 @@ scope_int=$(scope_to_digit "$CH_TEST_SCOPE")
 
 # Execute phase
 case $phase in
-    build)
-        builder_check
-        dir_tar_mk
-        test_make
-        test_build
-        win
-        ;;
-    run)
-        dir_img_mk
-        test_make
-        test_run
-        win
-        ;;
-    examples)
-        test_make
-        test_examples
-        win
-        ;;
     all)
         phase=build
         dir_tar_mk
@@ -917,6 +950,25 @@ case $phase in
         # Kobe.
         win
         ;;
+    build)
+        builder_check
+        dir_tar_mk
+        test_make
+        test_build
+        win
+        ;;
+    clean)
+        dirs_unpriv_rm
+        if [[ -d $TMP_ ]] && [[ -e $TMP_/build_auto.bats ]]; then
+            echo "removing $TMP_"
+            rm -rf --one-file-system "$TMP_"
+        fi
+        ;;
+    examples)
+        test_make
+        test_examples
+        win
+        ;;
     mk-perm-dirs)
         printf 'creating filesystem permissions fixtures ...\n'
         for d in $CH_TEST_PERMDIRS; do
@@ -929,16 +981,19 @@ case $phase in
         done
         echo
         ;;
+    one-file)
+        test_one_file
+        win
+        ;;
     rm-perm-dirs)
         for d in $CH_TEST_PERMDIRS; do
             dir_perm_rm "$d"
         done
         ;;
-    clean)
-        dirs_unpriv_rm
-        if [[ -d $TMP_ ]] && [[ -e $TMP_/build_auto.bats ]]; then
-            echo "removing $TMP_"
-            rm -rf --one-file-system "$TMP_"
-        fi
+    run)
+        dir_img_mk
+        test_make
+        test_run
+        win
         ;;
 esac
