fix prefix install bug

diff --git a/bin/ch-test b/bin/ch-test
--- a/bin/ch-test
+++ b/bin/ch-test
@@ -2,6 +2,7 @@
 
 set -e
 
+bin_=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
 libexec="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 . "${libexec}/base.sh"
 
@@ -19,10 +20,10 @@ builder_check () {
     printf 'checking builder ...\n'
     case $CH_BUILDER in
     ch-grow)
-        if ! ("${ch_bin}/ch-grow" --dependencies); then
+        if ! ("${bin_}/ch-grow" --dependencies); then
             fatal 'builder: ch-grow: missing dependencies'
         fi
-        bl=$(readlink -f "$ch_bin"/ch-grow)
+        bl=$(readlink -f "$bin_"/ch-grow)
         bv=$("$bl" --version)
         ;;
     buildah)
@@ -170,11 +171,11 @@ win () {
 }
 
 
-top_dir=$(readlink -f "${ch_bin%/*}")
+top_dir=$(readlink -f "${bin_%/*}")
 
 # Ensure ch-run has been compiled (issue #329).
-if (! "${ch_bin}/ch-run" --version &> /dev/null); then
-    fatal "ch-run not found; expected in $ch_bin"
+if (! "${bin_}/ch-run" --version &> /dev/null); then
+    fatal "ch-run not found; expected in $bin_"
 fi
 
 # Ensure we have Bash 4.1 or higher
@@ -197,7 +198,7 @@ if [[ -d ${top_dir}/test ]]; then
     testdir=${top_dir}/test
 else
     # prefix installation
-    testdir="${top_dir%/charliecloud*}/libexec/charliecloud-${ch_version}/test"
+    testdir="${top_dir}/libexec/charliecloud-${ch_version}/test"
 fi
 
 # Check for test directory.
@@ -261,8 +262,8 @@ while [[ $# -gt 0 ]]; do
 done
 
 printf "ch-test version %s\n\n" "$ch_version"
-printf 'ch-run: %s %s\n' "$("${ch_bin}/ch-run" --version 2>&1)" \
-                         "${ch_bin}/ch-run"
+printf 'ch-run: %s %s\n' "$("${bin_}/ch-run" --version 2>&1)" \
+                         "${bin_}/ch-run"
 printf 'bats:   %s %s\n' "$bats_version" "$bats"
 printf 'tests:  %s\n\n' "$testdir"
 
@@ -294,7 +295,7 @@ fi
 
 # Ensure namespaces are configured properly.
 printf 'checking namespaces ...\n'
-if (! "${ch_bin}/ch-checkns"); then
+if (! "${bin_}/ch-checkns"); then
     fatal 'namespace sanity check (ch-checkns) failed'
 fi
 printf '\n'
